strcompare:
	gcc -c strcompare.c -o strcompare.out
	./strcompare.out

strconcat:
	gcc -c strconcat.c -o strconcat.out
	./strconcat.out

strlenght:
	gcc -c strlenght.c -o strlenght.out
	./strlenght.out

clean:
	rm -f main main-debug